#!/usr/bin/env python3
"""make_evidence.py — build EVIDENCE.md from opi_bench.sh run folders.

Usage:  python3 make_evidence.py <results_dir>
  <results_dir>/raw/run_*/<mode>/...  (copied from /opt/opi_experiment/metrics on the host)
Writes <results_dir>/EVIDENCE.md: per run and mode, the verbatim lab lines that back
each claim (datapath config, a sample offloaded flow, every non-offloaded flow,
dpif/show and offload-stats excerpts, iperf3 totals). Quotes files; never invents.
"""
import json, os, re, sys

LABEL = {"sw": "L2 Arm kernel datapath, hw-offload=false (negative control)",
         "tc": "L3 Arm kernel datapath + TC offload (comparison)",
         "doca": "L4 OVS-DOCA datapath (contract primary path)"}


def read(path):
    try:
        with open(path, errors="replace") as f:
            return f.read()
    except OSError:
        return None


def flow_lines(txt):
    return [l for l in txt.splitlines() if l.startswith("ufid:") or "actions:" in l]


def block(title, body, limit=25):
    if not body:
        return [f"**{title}:** _not captured in this run_", ""]
    lines = body.rstrip().splitlines()
    cut = lines[:limit] + ([f"... ({len(lines) - limit} more lines)"] if len(lines) > limit else [])
    return [f"**{title}:**", "", "```", *cut, "```", ""]


def main(root):
    raw = os.path.join(root, "raw")
    runs = sorted(d for d in os.listdir(raw) if d.startswith("run_"))
    out = ["# Evidence excerpts (generated)", "",
           f"Generated by `artifacts/scripts/offload-bench/make_evidence.py` from `{os.path.relpath(raw, root)}/`.",
           "Every block below is copied verbatim from the raw run files. Regenerate rather than edit.", ""]
    for run in runs:
        rdir = os.path.join(raw, run)
        modes = [m for m in ("sw", "tc", "doca") if os.path.isdir(os.path.join(rdir, m))]
        if not modes:
            continue
        out += [f"## {run}", ""]
        for m in modes:
            d = os.path.join(rdir, m)
            out += [f"### {run} / {m} — {LABEL[m]}", ""]
            cfg = read(os.path.join(d, "ovs_config.txt")) or read(os.path.join(d, "arm_mode.txt"))
            if cfg:
                keep = [l for l in cfg.splitlines()
                        if re.search(r"hw-offload|doca|datapath_type|type=|mode ->|restarting", l)]
                out += block("Datapath configuration", "\n".join(keep), 30)
            flows = read(os.path.join(d, "flows_mid.txt")) or ""
            fl = flow_lines(flows)
            off = [l for l in fl if "offloaded:yes" in l]
            notoff = [l for l in fl if "offloaded:yes" not in l]
            dps = sorted(set(re.findall(r"dp:(\w+)", flows)))
            out += [f"**Flows mid-run (`ovs-appctl dpctl/dump-flows -m`):** {len(off)}/{len(fl)} "
                    f"with `offloaded:yes`; datapaths seen: {', '.join('`dp:'+x+'`' for x in dps) or 'none'}", ""]
            if off:
                out += block("Sample offloaded flow", off[0], 1)
            if notoff:
                out += block("Flows NOT offloaded (all listed)", "\n".join(notoff), 40)
            out += block("`ovs-appctl dpif/show` (mid-run)", read(os.path.join(d, "dpif_mid.txt")), 30)
            out += block("`ovs-appctl dpctl/offload-stats-show` (mid-run)",
                         read(os.path.join(d, "offload_stats_mid.txt")), 30)
            try:
                j = json.load(open(os.path.join(d, "iperf.json")))
                rx = j["end"]["sum_received"]["bits_per_second"] / 1e9
                rt = j["end"]["sum_sent"].get("retransmits")
                n = len(j["start"].get("connected", []))
                dur = j["start"]["test_start"].get("duration")
                out += [f"**iperf3:** {rx:.2f} Gbit/s received, {rt} retransmits, {n} streams, {dur}s", ""]
            except Exception as e:  # noqa: BLE001
                out += [f"**iperf3:** could not parse ({e})", ""]
    path = os.path.join(root, "EVIDENCE.md")
    with open(path, "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"wrote {path}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    main(sys.argv[1])
